language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
branches:
  only:
  - master
  - develop
before_install:
  - git clone -b develop --single-branch https://github.com/LearnLib/automatalib.git /tmp/automatalib-develop
  - pushd /tmp/automatalib-develop
  - mvn clean install
  - popd
install: true # skip mvn install, because we essentially run the same command in the script routine
script:
  - mvn verify -B -Pintegration-tests