language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
branches:
  only:
  - master
  - develop
before_install:
  - git clone -b develop --single-branch https://github.com/LearnLib/automatalib.git /tmp/automatalib-develop
  - pushd /tmp/automatalib-develop
    # skip several aspects of the build process, because we are only interested in the compiled code
  - mvn install -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true
  - popd
install: true # skip mvn install, because we essentially run the same command in the script routine
script:
  - mvn install -B -Pintegration-tests
